import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
// import logo
import Logo from "./f2.png";
import Link from "next/link";
import { ReduxProviders } from "./rtk/Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import test from "../../photos/sea-food-concept-banner-template/testbk5.jpg";

const rootLayoutStyle = {
  minHeight: "100vh",
  background: `url(${test.src})`, // Use the src property to get the image URL
  backgroundSize: "cover",
  backgroundPosition: "center",
};

//rtk

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={rootLayoutStyle}>
        <div className="min-h-full">
          <header className=" shadow">
            <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 flex items-center justify-between">
              <Link href="/">
                <div className="flex-shrink-0">
                  <Image
                    id="LogoNav"
                    src={Logo}
                    alt="Your Company"
                    width={100} // Adjust the width as needed
                    height={100} // Adjust the height as needed
                  />
                </div>
              </Link>
            </div>
          </header>

          <main>
            <div className="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
              <ReduxProviders>{children}</ReduxProviders>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
